language: python
python:
  #- "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
before script:
  - easy_install distribute
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - codecov
